FROM phusion/baseimage:0.11

{{content}}

WORKDIR /var/www/html

EXPOSE 80

CMD ["/sbin/my_init"]

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /etc/service/apache2
ADD apache2-foreground /etc/service/apache2/run
RUN chmod +x /etc/service/apache2/run